# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

networks:
  app-tier:
    driver: bridge

services: 

  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "FTaskPa55w0rd!"
      MSSQL_PID: "Express"
    ports:
      - "7433:1433"
    networks:
      - app-tier

  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - app-tier

  ftaskapi:
    image: ftaskapi
    build:
      context: .
      dockerfile: FTask.Api/Dockerfile
    ports:
      - "7000:80"
    # for production env 
    environment:
      - ASPNETCORE_ENVIRONMENT=Production  
    depends_on:
      - sqlserver
      - redis      
    networks:
      - app-tier