# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

networks: 
  localdev:
    name: localdev

services:
  ftaskapi:
    image: ftaskapi
    build:
      context: .
      dockerfile: FTask.Api/Dockerfile
    restart: always
    ports:
      - "7000:80"
    # for production env 
    environment:
      - ASPNETCORE_ENVIRONMENT=Production  
    depends_on:
      - sqlserver
      - redis
    networks: 
      - localdev

  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "FTaskPa55w0rd!"
      MSSQL_PID: "Express"
    ports:
      - "7433:1433"
    networks: 
      - localdev

  redis:
    image: redis
    container_name: redis
    ports: 
      - "6379:6379"